export const CATEGORY_COLORS: Record<string, string> = {
  'Groceries': '#58a6ff',
  'Restaurants': '#3b82f6',
  'Coffee & Cafes': '#8b5cf6',
  'Fast Food': '#f97316',
  'Bars & Alcohol': '#ef4444',
  'Gas & Fuel': '#eab308',
  'Public Transit': '#06b6d4',
  'Rideshare & Taxi': '#14b8a6',
  'Parking': '#6366f1',
  'Car Maintenance': '#a855f7',
  'Rent & Mortgage': '#ec4899',
  'Utilities': '#f43f5e',
  'Internet & Phone': '#10b981',
  'Insurance': '#0ea5e9',
  'Clothing': '#d946ef',
  'Electronics': '#2563eb',
  'Home & Garden': '#16a34a',
  'Pharmacy': '#dc2626',
  'Doctor & Dental': '#059669',
  'Gym & Fitness': '#7c3aed',
  'Subscriptions': '#0891b2',
  'Streaming': '#9333ea',
  'Movies & Events': '#c026d3',
  'Gaming': '#4f46e5',
  'Flights': '#0284c7',
  'Hotels': '#b45309',
  'Car Rental': '#0d9488',
  'Education': '#4338ca',
  'Gifts & Donations': '#be185d',
  'Pet Care': '#65a30d',
  'Personal Care': '#ea580c',
  'Bank & Fees': '#64748b',
  'Other': '#6b7280',
  'Uncategorized': '#484f58',
}

export const CATEGORY_GROUPS = [
  { label: 'Food', categories: ['Groceries', 'Restaurants', 'Coffee & Cafes', 'Fast Food', 'Bars & Alcohol'] },
  { label: 'Transportation', categories: ['Gas & Fuel', 'Public Transit', 'Rideshare & Taxi', 'Parking', 'Car Maintenance'] },
  { label: 'Housing', categories: ['Rent & Mortgage', 'Utilities', 'Internet & Phone', 'Insurance'] },
  { label: 'Shopping', categories: ['Clothing', 'Electronics', 'Home & Garden'] },
  { label: 'Health', categories: ['Pharmacy', 'Doctor & Dental', 'Gym & Fitness'] },
  { label: 'Entertainment', categories: ['Subscriptions', 'Streaming', 'Movies & Events', 'Gaming'] },
  { label: 'Travel', categories: ['Flights', 'Hotels', 'Car Rental'] },
  { label: 'Other', categories: ['Education', 'Gifts & Donations', 'Pet Care', 'Personal Care', 'Bank & Fees', 'Other'] },
]

export const ALL_CATEGORIES = Object.keys(CATEGORY_COLORS)
export const PAYMENT_METHODS = ['Card', 'Cash', 'Transfer', 'Debit'] as const
